### PR TITLE
Make this test actually pass

### PR DESCRIPTION
**Pull request by ljharb**

### CODE REVIEW

**Comment by spion** [comment]
The tests are pretty bad overall, but at least they test the right thing before the PR (that is, whether the modified tape correctly processes fulfilled / rejected promises). There *should* be one failing test for rejections.

Of course, the current way to test that is pretty bad, so I'm open to suggestions. The original tape actually tests the tap output, but I there has to be another, easier way...

**Comment by ljharb** [comment]
Gotcha - `npm test` needs to exit zero though, otherwise it's not useful imo. I'll think about it.

**Comment by tomekwi** [comment]
Perhaps generating and checking an [object stream](https://github.com/substack/tape/tree/aadcf4a95ed6810fa404dbe01f3b745252d4f12e#object-stream-reporter) is the way to go?

**Comment by spion** [comment]
@tomekwi yup, that was it, blue-tape now successfully tests itself :grinning:

**Pull request closed without merging**
