### PR TITLE
Add fails assertion

### PR DESCRIPTION
**Pull request by tuckerconnelly**
Addresses https://github.com/spion/blue-tape/issues/23

### CODE REVIEW

**Comment by spion** [comment]
There is already `t.fail` in tape, and it would be too confusing to name this method `fails`.

I think the following API would make sense:

```js
t.eventuallyRejects(promise, "message")
t.eventuallyRejectsWith(promise, ErrorType | errorTestFunction, "message")
```

**Comment by timoxley** [comment]
`shouldReject`

**Comment by tuckerconnelly** [comment]
Changed to `shouldReject` :)

**Comment by spion** [comment]
Great, a test or two and its good to go 👍

**Comment by tuckerconnelly** [comment]
Aight, added tests. Skipped adding scaffolding for messages :P

**Comment by tuckerconnelly** [comment]
@spion Can you merge this and release a new version on npm?

**Comment by spion** [comment]
Sorry for the delay. I wanted to merge this, then consolidate it into a single method

```js
t.shouldFail(promise P, optional class C, optional message|regex msg)
```

**Pull request merged**
